### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by North101** [pimoroni/pimoroni-pico-stubs#8]
Saw a comment on the discord that the README expects too much prior knowledge

**Comment by Gadgetoid** [comment]
Yeah, they're not wrong- I didn't expect anyone without that prior knowledge to be using these- I'm still losing daily fights with Thonny 😬 - but I guess they're pretty widely useful.

Looks like we need some guidance on:

* what kind of environment is expected
* how to install extensions
* how to access VSCode settings
* how and where to invoke `python3 -m site --user-site`

Also sheesh the repo contents don't half scroll the README out of view 😆 I think we should move the stubs into a subfolder and update the README to reflect that.

**Comment by Gadgetoid** [comment]
Had a crack at this here: https://github.com/pimoroni/pimoroni-pico-stubs/pull/9

**Comment by helgibbons** [comment]
It's still on my to-do list to write up a learn article about this - I've now got vscode + the MicroPico extension up and going and having access to these stubs (and Copilot) is really great!

**Comment by Pharkie** [comment]
Yeah.. that was my comment on the Discord 🫢

Thanks for the repo! Suggestions would be:

1) Add context at the start for someone new to VS Code like me = what are stubs, why do I need them, what does it change?
2) Where in VS Code do I enter the given JSON? (I found the JSON settings, after a search, but it was then unclear what level of indentation to use i.e. how to integrate the new JSON with the old JSON)
3) I translated the docs
`<pimoroni-pico-stubs> is the download location of this repo`
to 
```
To find your location, run in terminal: 

pip show micropython-rp2-pico-stubs
```

I can see some of this is already addressed in the waiting commit ✅

To be honest, I'm still unsure if I've actually installed these stubs.. How would I know? 😅

**Comment by North101** [comment]
I found this guide and following it, it allows importing without the `u` prefix:

https://micropython-stubs.readthedocs.io/en/latest/20_using.html#install-into-a-typings-folder
https://micropython-stubs.readthedocs.io/en/latest/22_vscode.html#

At some point i'll update the README with this info
